[build]
builder = "DOCKERFILE"
dockerfilePath = "express-api/Dockerfile"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"