[build]
builder = "NIXPACKS"
buildCommand = """
  curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
  apt-get install -y nodejs
  cd express-api && npm install
"""

[deploy]
startCommand = "node express-api/server.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"